name: Coverity Scan manual action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
          submodules: true
      - name: main
        env:
          COVERITY_SCRAPER_USER_EMAIL: ${{ secrets.COVERITY_SCRAPER_USER_EMAIL }}
          COVERITY_SCRAPER_PASS: ${{ secrets.COVERITY_SCRAPER_PASS }}
          COVERITY_PROJECT_NAME: ${{ secrets.COVERITY_PROJECT_NAME }}
          COVERITY_UPLOAD_TOKEN: ${{ secrets.COVERITY_UPLOAD_TOKEN }}
        run: |
          sudo apt install -y python3
          sudo apt install -y firefox
          sudo apt install -y python3-pip
          sudo apt install locate
          python3 -m pip install selenium
          python3 -m pip install webdriver-manager
          python3 -m pip install selenium-wire
          which firefox
          ./coverity_upload.sh
          python3 scrape_coverity_csv_browser.py
          echo "||||||||||||||||||||||||||||"
          locate Outstanding+Issues.csv
          echo "||||||||||||||||||||||||||||"
          ls -lrta ~/
        shell: bash
        working-directory: /home/runner/work/UnikraftScanning/UnikraftScanning/
